### PR TITLE
Feature/ws3

### PR DESCRIPTION
**Pull request by bzaar**
Is it same as my PR? I can see that you've removed token from config section. Shall I remove it from web config transformation too?

### CODE REVIEW

**Comment by SergeyFilenko** [comment]
Is it same as my PR? I can see that you've removed token from config section. Shall I remove it from web config trasformation too?

P.s. I've accidentally modified your message instead of posting new one, sorry.

**Comment by bzaar** [comment]
It's almost the same - I just removed insignificant differences.

> I can see that you've removed token from config section. Shall I remove it from web config trasformation too?

Please keep it. I have changed it to a non-existent GUID so that the user is forced to change it.

**Comment by bzaar** [comment]
Please give it a quick test and if happy, merge to master and release new Nuget packages.

I think it would be best to make `Morpher.WebService.V3` a separate Nuget package so we don't have to update `Morpher.API` when/if we need to update `Morpher.WebService.V3` (like now e.g.) 

Also, `*.Samples` will need to move to a separate GitHub repository because they depend on `Morpher.WebService.V3`.

**Comment by bzaar** [comment]
Let's call the factored-out `Morpher.WebService.V3` repository `Morpher.WebService.V3.Adaptor` to avoid a name clash with the existing repo. Also, let's rename class `Client` to `Adaptor`.

**Comment by bzaar** [comment]
The adaptor has been implemented in a separate repo: [Morpher.WebService.V3.Adaptor](https://github.com/morpher-ru/Morpher.WebService.V3.Adaptor).

**Pull request closed without merging**
